export interface JustWatchRegion {
  code: string;
  label: string;
}

export interface JustWatchRegionGroup {
  label: string;
  regions: JustWatchRegion[];
}

// Source: JustWatch public "available in" country list.
export const JUSTWATCH_REGION_GROUPS: JustWatchRegionGroup[] = [
  {
    label: 'North America',
    regions: [
      { code: 'bm', label: 'Bermuda' },
      { code: 'ca', label: 'Canada' },
      { code: 'mx', label: 'Mexico' },
      { code: 'us', label: 'United States' },
    ],
  },
  {
    label: 'South America',
    regions: [
      { code: 'ar', label: 'Argentina' },
      { code: 'bo', label: 'Bolivia' },
      { code: 'br', label: 'Brazil' },
      { code: 'cl', label: 'Chile' },
      { code: 'co', label: 'Colombia' },
      { code: 'ec', label: 'Ecuador' },
      { code: 'gf', label: 'French Guiana' },
      { code: 'gy', label: 'Guyana' },
      { code: 'py', label: 'Paraguay' },
      { code: 'pe', label: 'Peru' },
      { code: 'uy', label: 'Uruguay' },
      { code: 've', label: 'Venezuela' },
    ],
  },
  {
    label: 'Europe',
    regions: [
      { code: 'al', label: 'Albania' },
      { code: 'ad', label: 'Andorra' },
      { code: 'at', label: 'Austria' },
      { code: 'az', label: 'Azerbaijan' },
      { code: 'by', label: 'Belarus' },
      { code: 'be', label: 'Belgium' },
      { code: 'ba', label: 'Bosnia and Herzegovina' },
      { code: 'bg', label: 'Bulgaria' },
      { code: 'hr', label: 'Croatia' },
      { code: 'cy', label: 'Cyprus' },
      { code: 'cz', label: 'Czech Republic' },
      { code: 'dk', label: 'Denmark' },
      { code: 'ee', label: 'Estonia' },
      { code: 'fi', label: 'Finland' },
      { code: 'fr', label: 'France' },
      { code: 'de', label: 'Germany' },
      { code: 'gi', label: 'Gibraltar' },
      { code: 'gr', label: 'Greece' },
      { code: 'gg', label: 'Guernsey' },
      { code: 'hu', label: 'Hungary' },
      { code: 'is', label: 'Iceland' },
      { code: 'ie', label: 'Ireland' },
      { code: 'it', label: 'Italy' },
      { code: 'xk', label: 'Kosovo' },
      { code: 'lv', label: 'Latvia' },
      { code: 'li', label: 'Liechtenstein' },
      { code: 'lt', label: 'Lithuania' },
      { code: 'lu', label: 'Luxembourg' },
      { code: 'mk', label: 'Macedonia' },
      { code: 'mt', label: 'Malta' },
      { code: 'md', label: 'Moldova' },
      { code: 'mc', label: 'Monaco' },
      { code: 'me', label: 'Montenegro' },
      { code: 'nl', label: 'Netherlands' },
      { code: 'no', label: 'Norway' },
      { code: 'pl', label: 'Poland' },
      { code: 'pt', label: 'Portugal' },
      { code: 'ro', label: 'Romania' },
      { code: 'ru', label: 'Russia' },
      { code: 'sm', label: 'San Marino' },
      { code: 'rs', label: 'Serbia' },
      { code: 'sk', label: 'Slovakia' },
      { code: 'si', label: 'Slovenia' },
      { code: 'es', label: 'Spain' },
      { code: 'se', label: 'Sweden' },
      { code: 'ch', label: 'Switzerland' },
      { code: 'tr', label: 'Turkey' },
      { code: 'ua', label: 'Ukraine' },
      { code: 'gb', label: 'United Kingdom' },
      { code: 'va', label: 'Vatican City' },
    ],
  },
  {
    label: 'Asia',
    regions: [
      { code: 'hk', label: 'Hong Kong' },
      { code: 'in', label: 'India' },
      { code: 'id', label: 'Indonesia' },
      { code: 'jp', label: 'Japan' },
      { code: 'lb', label: 'Lebanon' },
      { code: 'my', label: 'Malaysia' },
      { code: 'pk', label: 'Pakistan' },
      { code: 'ph', label: 'Philippines' },
      { code: 'sg', label: 'Singapore' },
      { code: 'kr', label: 'South Korea' },
      { code: 'tw', label: 'Taiwan' },
      { code: 'th', label: 'Thailand' },
    ],
  },
  {
    label: 'Central America',
    regions: [
      { code: 'bz', label: 'Belize' },
      { code: 'cr', label: 'Costa Rica' },
      { code: 'sv', label: 'El Salvador' },
      { code: 'gt', label: 'Guatemala' },
      { code: 'hn', label: 'Honduras' },
      { code: 'ni', label: 'Nicaragua' },
      { code: 'pa', label: 'Panama' },
    ],
  },
  {
    label: 'Africa',
    regions: [
      { code: 'dz', label: 'Algeria' },
      { code: 'ao', label: 'Angola' },
      { code: 'bf', label: 'Burkina Faso' },
      { code: 'cm', label: 'Cameroon' },
      { code: 'cv', label: 'Cape Verde' },
      { code: 'td', label: 'Chad' },
      { code: 'gq', label: 'Equatorial Guinea' },
      { code: 'gh', label: 'Ghana' },
      { code: 'ci', label: 'Ivory Coast' },
      { code: 'ke', label: 'Kenya' },
      { code: 'ly', label: 'Libya' },
      { code: 'mg', label: 'Madagascar' },
      { code: 'mw', label: 'Malawi' },
      { code: 'ml', label: 'Mali' },
      { code: 'mu', label: 'Mauritius' },
      { code: 'ma', label: 'Morocco' },
      { code: 'mz', label: 'Mozambique' },
      { code: 'ne', label: 'Niger' },
      { code: 'ng', label: 'Nigeria' },
      { code: 'sn', label: 'Senegal' },
      { code: 'sc', label: 'Seychelles' },
      { code: 'za', label: 'South Africa' },
      { code: 'tz', label: 'Tanzania' },
      { code: 'tn', label: 'Tunisia' },
      { code: 'ug', label: 'Uganda' },
      { code: 'zm', label: 'Zambia' },
      { code: 'zw', label: 'Zimbabwe' },
    ],
  },
  {
    label: 'Pacific',
    regions: [
      { code: 'au', label: 'Australia' },
      { code: 'fj', label: 'Fiji' },
      { code: 'pf', label: 'French Polynesia' },
      { code: 'nz', label: 'New Zealand' },
      { code: 'pg', label: 'Papua New Guinea' },
    ],
  },
  {
    label: 'Middle East',
    regions: [
      { code: 'bh', label: 'Bahrain' },
      { code: 'eg', label: 'Egypt' },
      { code: 'iq', label: 'Iraq' },
      { code: 'il', label: 'Israel' },
      { code: 'jo', label: 'Jordan' },
      { code: 'kw', label: 'Kuwait' },
      { code: 'om', label: 'Oman' },
      { code: 'ps', label: 'Palestine' },
      { code: 'qa', label: 'Qatar' },
      { code: 'sa', label: 'Saudi Arabia' },
      { code: 'ae', label: 'United Arab Emirates' },
      { code: 'ye', label: 'Yemen' },
    ],
  },
];

export const JUSTWATCH_REGIONS = JUSTWATCH_REGION_GROUPS.flatMap(group => group.regions);
export const JUSTWATCH_REGION_CODES = new Set(JUSTWATCH_REGIONS.map(region => region.code));
